### PR TITLE
Better Python 3 support

### PR DESCRIPTION
**Pull request by streeter**

### CODE REVIEW

**Comment by streeter** [comment]
I signed it!

**Comment by erlichmen** [comment]
Committers, pls expect this PR py3 support is really needed.

**Comment by BrandonY** [comment]
Looks good to me.

**Comment by rajasimon** [comment]
This is not available in `googleappenginecloudstorageclient==1.9.22.1` release right ? Then when do I expect this ?  

It 's so hard to deploy without that I'm running on Python3.6 Flexible appengine. Help me here.

**Comment by frankyn** [comment]
@rajasimon, IIUC, you're running Python 3.6 on Google Appengine flexible environment. If this is correct, you should use the [Google Cloud Python client library](https://github.com/GoogleCloudPlatform/google-cloud-python) and not this Appengine GCS client library as it's meant for Google Appengine standard environment.

**Comment by rajasimon** [comment]
Thanks for your response. I started using Google cloud python client library.

**Pull request merged**
